# .streamlit/secrets.toml
[streamlit]
deployment_mode = "production"

[firebase]
max_cache_age = 60
apiKey = ""
authDomain = ""
databaseURL = ""
project_id = ""
storageBucket = ""
messagingSenderId = ""
appId = ""
private_key = ""
client_email = ""
private_key_id = ""
auth_uri = ""
token_uri = ""
